{{- if .Values.hyperdx.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hdx-oss.fullname" . }}-app-ingress
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if .Values.hyperdx.ingress.tls.enabled }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.hyperdx.ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.hyperdx.ingress.proxyConnectTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.hyperdx.ingress.proxySendTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.hyperdx.ingress.proxyReadTimeout | quote }}
spec:
  ingressClassName: nginx
  {{- if .Values.hyperdx.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.hyperdx.ingress.host | default "localhost" }}
    secretName: {{ .Values.hyperdx.ingress.tlsSecretName | default "hyperdx-tls" }}
  {{- end }}
  rules:
    - host: {{ .Values.hyperdx.ingress.host | default "localhost" }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "hdx-oss.fullname" . }}-app
                port:
                  number: {{ .Values.hyperdx.appPort }}
{{- range .Values.hyperdx.ingress.additionalIngresses}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "hdx-oss.fullname" $) .name }}
  labels:
    {{- include "hdx-oss.labels" $ | nindent 4 }}
  {{- if .annotations }}
  {{- if not (kindIs "map" .annotations) }}
  {{- fail "annotations must be a map of string key-value pairs" }}
  {{- end }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end -}}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    {{- if not .hosts }}
    {{- fail "TLS configuration must contain hosts property" }}
    {{- end }}
    - hosts:
        {{- range .hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      {{- with .secretName }}
      secretName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if or (not .path) (not .pathType) (not .port) }}
          {{- fail "Each path in additional ingress must contain path, pathType, and port properties" }}
          {{- end }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "hdx-oss.fullname" $ }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
