{{- if .Values.otel.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hdx-oss.fullname" . }}-otel-collector
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hdx-oss.selectorLabels" . | nindent 6 }}
      app: otel-collector
  template:
    metadata:
      labels:
        {{- include "hdx-oss.selectorLabels" . | nindent 8 }}
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.otel.image }}"
          ports:
            - containerPort: {{ .Values.otel.port }}
            - containerPort: {{ .Values.otel.nativePort }}
            - containerPort: {{ .Values.otel.grpcPort }}
            - containerPort: {{ .Values.otel.httpPort }}
            - containerPort: {{ .Values.otel.healthPort }}
          env:
            - name: CLICKHOUSE_ENDPOINT
              value: "{{ .Values.otel.clickhouseEndpoint | default (printf "tcp://%s-clickhouse:%v?dial_timeout=10s" (include "hdx-oss.fullname" .) .Values.clickhouse.nativePort) }}"
            - name: CLICKHOUSE_SERVER_ENDPOINT
              value: "{{ .Values.otel.clickhouseEndpoint | default (printf "%s-clickhouse:%v" (include "hdx-oss.fullname" .) .Values.clickhouse.nativePort) }}"
            {{- if .Values.clickhouse.prometheus.enabled }}
            - name: CLICKHOUSE_PROMETHEUS_METRICS_ENDPOINT
              value: "{{ .Values.otel.clickhousePrometheusEndpoint | default (printf "%s-clickhouse:%v" (include "hdx-oss.fullname" .) .Values.clickhouse.prometheus.port ) }}"
            {{- end }}
            - name: OPAMP_SERVER_URL
              value: {{ .Values.otel.opampServerUrl | default (printf "http://%s-app:%v" (include "hdx-oss.fullname" .) .Values.hyperdx.opampPort ) }}
            - name: HYPERDX_LOG_LEVEL
              value: {{ .Values.hyperdx.logLevel }}
            - name: HYPERDX_OTEL_EXPORTER_CLICKHOUSE_DATABASE
              value: {{ .Values.otel.clickhouseDatabase | default "default" }}
            - name: HYPERDX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hdx-oss.fullname" . }}-app-secrets
                  key: api-key
            - name: CLICKHOUSE_USER
              value: "otelcollector"
            - name: CLICKHOUSE_PASSWORD
              value: {{ .Values.clickhouse.config.users.otelUserPassword }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdx-oss.fullname" . }}-otel-collector
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.otel.port }}
      targetPort: {{ .Values.otel.port }}
      name: health
    - port: {{ .Values.otel.nativePort }}
      targetPort: {{ .Values.otel.nativePort }}
      name: fluentd
    - port: {{ .Values.otel.grpcPort }}
      targetPort: {{ .Values.otel.grpcPort }}
      name: otlp-grpc
    - port: {{ .Values.otel.httpPort }}
      targetPort: {{ .Values.otel.httpPort }}
      name: otlp-http
    - port: {{ .Values.otel.healthPort }}
      targetPort: {{ .Values.otel.healthPort }}
      name: metrics
  selector:
    {{- include "hdx-oss.selectorLabels" . | nindent 4 }}
    app: otel-collector
{{- end }}