apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hdx-oss.fullname" . }}-app-config
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
data:
  APP_PORT: {{ .Values.hyperdx.appPort | quote }}
  API_PORT: {{ .Values.hyperdx.apiPort | quote }}
  {{- if .Values.hyperdx.ingress.enabled }}
  FRONTEND_URL: "{{ if .Values.hyperdx.ingress.tls.enabled }}https{{ else }}http{{ end }}://{{ .Values.hyperdx.ingress.host }}"
  {{- else }}
  FRONTEND_URL: "{{ .Values.hyperdx.appUrl }}:{{ .Values.hyperdx.appPort }}"
  {{- end }}
  HYPERDX_API_PORT: "{{ .Values.hyperdx.apiPort }}"
  HYPERDX_APP_PORT: "{{ .Values.hyperdx.appPort }}"
  HYPERDX_APP_URL: "{{ .Values.hyperdx.appUrl }}"
  HYPERDX_LOG_LEVEL: "{{ .Values.hyperdx.logLevel }}"
  MINER_API_URL: "http://{{ include "hdx-oss.fullname" . }}-miner:5123"
  MONGO_URI: "{{ tpl .Values.hyperdx.mongoUri . }}"
  OTEL_SERVICE_NAME: "hdx-oss-api"
  USAGE_STATS_ENABLED: "{{ .Values.hyperdx.usageStatsEnabled | default true }}"
  CRON_IN_APP_DISABLED: "{{ .Values.tasks.enabled | default false }}"
  OPAMP_PORT: "{{ .Values.hyperdx.opampPort }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ tpl .Values.hyperdx.otelExporterEndpoint . }}"
