# Configuration using external secrets for connections and sources
# Usage: ./scripts/e2e-ingress-test.sh --config examples/values-with-secrets.yaml

hyperdx:
  # These will be overridden by the script with actual domain
  appUrl: "PLACEHOLDER_DOMAIN"
  frontendUrl: "PLACEHOLDER_DOMAIN"
  
  ingress:
    enabled: true
    ingressClassName: nginx
    path: "/(.*)"
    pathType: "ImplementationSpecific"
    annotations: {}
    tls:
      enabled: false

  # Use external secrets instead of inline configuration
  useExistingConfigSecret: true
  existingConfigSecret: "hyperdx-config-secret"
  existingConfigConnectionsKey: "connections.json"
  existingConfigSourcesKey: "sources.json"
  
  # Clear default connections and sources since we're using secrets
  defaultConnections: ""
  defaultSources: ""

# Minimal resources for testing
mongodb:
  persistence:
    enabled: true
    dataSize: 1Gi

clickhouse:
  persistence:
    enabled: true
    dataSize: 1Gi

# OTEL collector
otel:
  enabled: true