{{- if .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hdx-oss.fullname" . }}-mongodb
  labels:
    {{- include "hdx-oss.labels" . | nindent 4 }}
  {{- if .Values.global.keepPVC }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.dataSize }}
---
{{- end }}
