name: Helm Chart Integration Test

on:
  # Run on merge to main
  push:
    branches: [ main ]
  # Run on pull requests
  pull_request:
    branches: [ main ]
  # Run nightly at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: '3.12.0'

    - name: Update appVersion for nightly builds
      if: github.event_name == 'schedule'
      run: |
        echo "Updating appVersion to 2-nightly for scheduled builds"
        sed -i 's/^appVersion:.*/appVersion: 2-nightly/' charts/hdx-oss-v2/Chart.yaml
        echo "Updated Chart.yaml:"
        cat charts/hdx-oss-v2/Chart.yaml

    - name: Create kind cluster config
      run: |
        cat > kind-config.yaml << EOF
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
          extraPortMappings:
          - containerPort: 30000
            hostPort: 3000
            protocol: TCP
          - containerPort: 30001
            hostPort: 4318
            protocol: TCP
        EOF

    - name: Create kind cluster
      uses: helm/kind-action@v1
      with:
        cluster_name: hyperdx-test
        config: kind-config.yaml

    - name: Install local-path-provisioner
      run: |
        kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
        kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

    - name: Run Helm unit tests
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git || true
        helm unittest charts/hdx-oss-v2

    - name: Deploy HyperDX chart
      run: |
        # Create test values for faster deployment
        cat > test-values.yaml << EOF
        hyperdx:
          apiKey: "test-api-key-for-ci"
          frontendUrl: "http://localhost:3000"
          replicas: 1
          service:
            type: NodePort
            nodePort: 30000
          env:
            - name: IS_LOCAL_APP_MODE
              value: "DANGEROUSLY_is_local_app_mode💀"

        clickhouse:
          persistence:
            enabled: true
            dataSize: 2Gi
            logSize: 1Gi

        mongodb:
          persistence:
            enabled: true
            dataSize: 2Gi

        otel:
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
        EOF

        # Install the chart
        helm install hyperdx-test ./charts/hdx-oss-v2 -f test-values.yaml --timeout=5m

        # Give services time to initialize after pods are running
        echo "Waiting for services to initialize..."
        sleep 20

    - name: Verify deployment
      run: |
        # Check initial pod status
        echo "Initial pod status:"
        kubectl get pods -o wide
        
        # Wait for ClickHouse and MongoDB first (OTEL collector dependencies)
        echo "Waiting for ClickHouse and MongoDB to be ready..."
        kubectl wait --for=condition=Ready pods -l app=clickhouse --timeout=300s
        kubectl wait --for=condition=Ready pods -l app=mongodb --timeout=300s
        
        # Wait for HyperDX app to be ready (OpAMP server)
        echo "Waiting for HyperDX app to be ready..."
        kubectl wait --for=condition=Ready pods -l app=hyperdx-test-hdx-oss-v2 --timeout=300s
        
        # Test OpAMP server connectivity
        echo "Testing OpAMP server connectivity..."
        kubectl exec -n default deployment/hyperdx-test-hdx-oss-v2-app -- curl -f http://localhost:4320 || echo "OpAMP server not yet ready"
        
        # Wait for OpAMP server to fully initialize
        echo "Waiting for OpAMP server to initialize..."
        sleep 30
        
        # Test OpAMP server again
        kubectl exec -n default deployment/hyperdx-test-hdx-oss-v2-app -- curl -f http://localhost:4320 || echo "OpAMP server connectivity issue"
        
        # Now wait for OTEL collector to be ready
        echo "Waiting for OTEL collector..."
        kubectl wait --for=condition=Ready pods -l app=otel-collector --timeout=300s

        # Check final pod status
        echo "Final pod status:"
        kubectl get pods -o wide

        # Check services
        kubectl get services

    - name: Run comprehensive smoke tests
      run: |
        # Make smoke test script executable
        chmod +x ./scripts/smoke-test.sh

        # Run the smoke test with CI-specific environment
        RELEASE_NAME=hyperdx-test NAMESPACE=default ./scripts/smoke-test.sh

    - name: Collect logs on failure
      if: failure()
      run: |
        echo "=== Pod Status ==="
        kubectl get pods -o wide

        echo "=== Events ==="
        kubectl get events --sort-by=.metadata.creationTimestamp

        echo "=== HyperDX App Logs ==="
        kubectl logs -l app=app --tail=100 || true

        echo "=== ClickHouse Logs ==="
        kubectl logs -l app=clickhouse --tail=100 || true

        echo "=== MongoDB Logs ==="
        kubectl logs -l app=mongodb --tail=100 || true

        echo "=== OTEL Collector Logs ==="
        kubectl logs -l app=otel-collector --tail=100 || true

    - name: Cleanup
      if: always()
      run: |
        helm uninstall hyperdx-test || true
        kind delete cluster --name hyperdx-test || true
