name: Release Helm Charts
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git user
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          commit: 'chore(release): bump version'
          title: 'Release HyperDX Helm Charts'
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run chart-releaser job
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
